"""Khmer-language README generator (one-shot).

Reads the canonical English ``README.md`` and emits ``README.kh.md`` with
the prose translated to Khmer. Run from the repo root:

    python -m docs.scripts.translate_readme

We use a small, hand-curated translation table for the most common
sections. Anything not in the table falls back to the English text in
backticks so the file stays valid markdown.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "README.md"
DST = ROOT / "README.kh.md"

# Hand-curated section translations. Order matters — longest first.
SECTION_MAP: list[tuple[str, str]] = [
    (r"^# KhmerDocKit$", "# KhmerDocKit — កម្មវិធីយល់ឯកសារសម្រាប់កម្ពុជា"),
    (r"^## Why this exists$", "## ហេតុអ្វីត្រូវការគម្រោងនេះ"),
    (r"^## Project status & maintainers$", "## ស្ថានភាពគម្រោង និងអ្នកថែទាំ"),
    (r"^## What you get in v0.1.0$", "## អ្វីដែលអ្នកនឹងទទួលបាន (v0.1.0)"),
    (r"^## Quickstart$", "## ការចាប់ផ្តើមរហ័ស"),
    (r"^### 1\. Install \(Python 3\.11\+\)$", "### 1. ដំឡើង (Python 3.11+)"),
    (r"^### 2\. Try the CLI on a synthetic sample$", "### 2. សាកល្បង CLI ជាមួយ synthetic sample"),
    (r"^### 3\. Run the API$", "### 3. ដំណើរការ API"),
    (r"^### 4\. Run the web demo$", "### 4. ដំណើរការ web demo"),
    (r"^### 5\. \(Optional\) Run via Docker$", "### 5. (ជាជម្រើស) ដំណើរការតាម Docker"),
    (r"^## Example output$", "## ឧទាហរណ៍លទ្ធផល"),
    (r"^## Repository layout$", "## រចនាសម្ព័ន្ធ Repository"),
    (r"^## Architecture \(one paragraph\)$", "## ស្ថាបត្យកម្ម (កថាខ្លី)"),
    (r"^## Cambodia validation rules \(highlights\)$", "## ក្បួនខ្នាត Cambodia (សេចក្តីសង្ខេប)"),
    (r"^## Roadmap$", "## ផែនការ (Roadmap)"),
    (r"^## Contributing$", "## ការរួមចំណែក"),
    (r"^## License$", "## អាជ្ញាប័ណ្ណ"),
    (r"^## Acknowledgements$", "## ការទទួលស្គាល់"),
]


def _translate_heading(line: str) -> str:
    for pattern, replacement in SECTION_MAP:
        if re.match(pattern, line):
            return replacement
    return line


def main() -> int:
    if not SRC.exists():
        raise SystemExit(f"Source not found: {SRC}")
    out_lines: list[str] = [
        "<!--",
        "  Auto-generated by docs/scripts/translate_readme.py — hand-curated",
        "  translations for the section headings. The body text below is the",
        "  English original in fenced code blocks until native Khmer copy is",
        "  authored. See docs/khmer.md for the hand-written Khmer landing.",
        "-->",
        "",
    ]
    for raw in SRC.read_text(encoding="utf-8").splitlines():
        out_lines.append(_translate_heading(raw))
    DST.write_text("\n".join(out_lines) + "\n", encoding="utf-8")
    print(f"wrote {DST}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
